### ISSUE TITLE
Some problems in QuantSR

### ISSUE THREAD

**Issue by cheng221** [htqin/QuantSR#2]
Congratulations on the acceptance of your paper! I've read the initial draft of your paper on OpenReview, and I have three questions to ask you:

1. Have you applied other SR quantization methods, such as PAMS, to Transformer and compared the results with your QuantSR-T? It seems that the results were not compared in your paper.

2. In Table 2, the results of the DoReFa 2-bit quantization on the x4 SR network show higher accuracy than the results with a 4-bit quantization. Is there an issue with this?

3. The introduction of DAQ in the paper is not detailed enough, and it's unclear how it skips certain layers. The corresponding code for this part has also not been made available.

**Comment by htqin** [comment]
Hi, thanks for your attention! (1) Yes. Since our GPU resources are limited, we didn't present the full results of other methods (like PAMS) on the transformer, but some early-stopped results show the existing methods are much worse than the proposed QuantSR-T. (2) We quickly checked the results, and it seems that the 4-bit and 2-bit results of DoReFa on the x2 scale should be exchanged. We'll carefully check the original models/results later. (3) The key mechanism of our DAQ can be clarified at https://github.com/htqin/QuantSR/blob/main/basicsr/archs/arch_util.py#L139-L151 . The skipped QuantSR block only retains the shortcut instead of the convolution computation. We will clarify our code further to make it easier to read in the future.

We hope the reply could be helpful. Thank you again for your attention!

**Comment by cheng221** [comment]
> Hi, thanks for your attention! (1) Yes. Since our GPU resources are limited, we didn't present the full results of other methods (like PAMS) on the transformer, but some early-stopped results show the existing methods are much worse than the proposed QuantSR-T. (2) We quickly checked the results, and it seems that the 4-bit and 2-bit results of DoReFa on the x2 scale should be exchanged. We'll carefully check the original models/results later. (3) The key mechanism of our DAQ can be clarified at https://github.com/htqin/QuantSR/blob/main/basicsr/archs/arch_util.py#L139-L151 . The skipped QuantSR block only retains the shortcut instead of the convolution computation. We will clarify our code further to make it easier to read in the future.
> 
> We hope the reply could be helpful. Thank you again for your attention!

Have a good day! Thank you for your kind reply! Your answer has resolved my doubts, and I hope that the issue in Q2 can be addressed in future versions of the paper.
